### ISSUE TITLE
Where to grant the public permissions

### ISSUE THREAD

**Issue by stefanwuthrich** [swensonhe/strapi-firebase-auth#53]
I got the plugin accepting the json etc, but when I access the Firebase Plugin Section (User Grid) or want to setup a user from there, I get just errors.
What I could not manage is to grant the permissions as described at step 5 in your (great) doc.
I can not find in Strapi (newest version), where to set the URL. I can only find this:
![image](https://github.com/swensonhe/strapi-firebase-auth/assets/8337826/de0c931c-068b-49e5-b7e6-e3428eda1e49)

Any idea what I miss?

**Comment by stefanwuthrich** [comment]
in strapi log i see

[2024-01-22 08:00:31.687] http: GET /firebase-auth/users?pagination[page]=1&pagination[pageSize]=10 (8 ms) 500
[2024-01-22 08:00:31.758] error: Cannot read properties of undefined (reading 'auth')
TypeError: Cannot read properties of undefined (reading 'auth')
    at /home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:142:30
    at step (/home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:33:23)
    at Object.next (/home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:14:53)
    at /home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:4:12)
    at Object.list (/home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/userService.js:137:61)
    at /home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/controllers/userController.js:62:30
    at step (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/controllers/userController.js:33:23)
    at Object.next (/home/stefan/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/controllers/userController.js:14:53)

**Comment by stefanwuthrich** [comment]
some more info 

✔ Creating admin (12575ms)
⠇ Loading Strapibootstrap error --> FirebaseAppError: Service account object must contain a string "private_key" property.
    at new ServiceAccount (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/firebase-admin@11.11.1/node_modules/firebase-admin/lib/app/credential-internal.js:145:19)
    at new ServiceAccountCredential (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/firebase-admin@11.11.1/node_modules/firebase-admin/lib/app/credential-internal.js:70:15)
    at Object.cert (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/firebase-admin@11.11.1/node_modules/firebase-admin/lib/app/credential-factory.js:103:54)
    at Object.<anonymous> (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/settingsService.js:86:81)
    at step (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/settingsService.js:33:23)
    at Object.next (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/settingsService.js:14:53)
    at fulfilled (/home/stefan/go/src/github.com/altafino/systemak-app/strapi-cms/node_modules/.pnpm/@swensonhe+strapi-plugin-firebase-auth@1.0.8_@babel+runtime@7.23.8_@lezer+common@1.2.1_@strap_tpn7ppzykrh7j7pig4kkylkh2q/node_modules/@swensonhe/strapi-plugin-firebase-auth/server/services/settingsService.js:5:58) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Service account object must contain a string "private_key" property.'
  },
  codePrefix: 'app'
}
✔ Loading Strapi (13487ms)
✔ Generating types (283ms)

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Jan 25 2024 01:07:03 GMT-0300 (Brasilia Sta… │
│ Launched in        │ 13784 ms                                         │
│ Environment        │ development                                      │
│ Process PID        │ 79941                                            │
│ Version            │ 4.17.1 (node v20.10.0)                           │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
